apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memory-hog-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: '[YOUR_GITHUB_REPO_URL]' # e.g., https://github.com/username/project_devops.git
    targetRevision: HEAD
    path: k8s # The path where the deployment.yaml is stored
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
